workflows:
  ios-workflow:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install Pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build Unsigned IPA
        script: |
          # 1. Build the iOS app without code signing
          flutter build ios --release --no-codesign

          # 2. Create the Payload folder structure required for an IPA
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload

          # 3. Zip it into an .ipa file
          zip -r Runner.ipa Payload

          # 4. Move it to the root so Codemagic can find it
          mv Runner.ipa $CM_BUILD_DIR/Runner.ipa
    artifacts:
      - Runner.ipa