workflows:
  ios-workflow:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Unsigned IPA
        script: |
          # 1. Build the iOS app
          flutter build ios --release --no-codesign

          # 2. The .app is built to this specific location
          APP_PATH="build/ios/iphoneos/Runner.app"

          # 3. Verify the app bundle exists and contains an executable
          if [ ! -d "$APP_PATH" ]; then
            echo "ERROR: Runner.app not found at $APP_PATH"
            find build -name "*.app" -type d
            exit 1
          fi

          if [ ! -f "$APP_PATH/Runner" ]; then
            echo "ERROR: Runner executable not found inside app bundle"
            ls -la "$APP_PATH"
            exit 1
          fi

          echo "App bundle found with contents:"
          ls -la "$APP_PATH"

          # 4. Prepare the Payload folder structure
          rm -rf Payload
          mkdir -p Payload

          # 5. Copy the app bundle (preserve symlinks with -R)
          cp -R "$APP_PATH" Payload/

          # 6. Create the IPA (zip with symlinks preserved)
          zip -r -y Runner.ipa Payload

          # 7. Verify IPA structure
          echo "IPA contents:"
          unzip -l Runner.ipa | head -20

          # 8. Move to artifacts location
          mv Runner.ipa $CM_BUILD_DIR/Runner.ipa
    artifacts:
      - Runner.ipa