workflows:
  ios-workflow:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 16.2
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Build Unsigned IPA
        script: |
          # 1. Generate Flutter iOS build files
          flutter build ios --release --no-codesign || true

          # 2. If Flutter build failed to create .app, use xcodebuild directly
          APP_PATH="build/ios/iphoneos/Runner.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "Flutter build incomplete, using xcodebuild..."
            cd ios
            xcodebuild -workspace Runner.xcworkspace \
              -scheme Runner \
              -configuration Release \
              -sdk iphoneos \
              -destination 'generic/platform=iOS' \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              DEVELOPMENT_TEAM="" \
              PROVISIONING_PROFILE_SPECIFIER="" \
              ONLY_ACTIVE_ARCH=NO \
              BUILD_DIR="../build/ios"
            cd ..
            APP_PATH="build/ios/Release-iphoneos/Runner.app"
          fi

          # 3. Check both possible locations for the .app
          if [ ! -d "$APP_PATH" ]; then
            APP_PATH="build/ios/Release-iphoneos/Runner.app"
          fi

          # 4. Verify the app bundle exists and contains an executable
          if [ ! -d "$APP_PATH" ]; then
            echo "ERROR: Runner.app not found at $APP_PATH"
            echo "Searching for .app bundles:"
            find build -name "*.app" -type d
            exit 1
          fi

          if [ ! -f "$APP_PATH/Runner" ]; then
            echo "ERROR: Runner executable not found inside app bundle"
            ls -la "$APP_PATH"
            exit 1
          fi

          echo "App bundle found with contents:"
          ls -la "$APP_PATH"

          # 5. Fake-sign all binaries for AltStore compatibility
          echo "Fake-signing app bundle for AltStore..."

          # Sign the main executable
          /usr/bin/codesign --force --deep --sign - "$APP_PATH"

          # Sign all frameworks
          find "$APP_PATH/Frameworks" -name "*.framework" -type d | while read framework; do
            echo "Signing framework: $framework"
            /usr/bin/codesign --force --deep --sign - "$framework"
          done

          echo "Fake-signing complete"

          # 6. Prepare the Payload folder structure
          rm -rf Payload
          mkdir -p Payload

          # 7. Copy the app bundle (preserve symlinks with -R)
          cp -R "$APP_PATH" Payload/

          # 8. Create the IPA (zip with symlinks preserved)
          zip -r -y Runner.ipa Payload

          # 9. Verify IPA structure
          echo "IPA contents:"
          unzip -l Runner.ipa | head -20

          # 10. Move to artifacts location
          mv Runner.ipa $CM_BUILD_DIR/Runner.ipa
    artifacts:
      - Runner.ipa