import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../theme.dart';
import '../sports_alerts/data/team_colors.dart';
import '../sports_alerts/models/game_state.dart';
import '../sports_alerts/models/score_alert_config.dart';
import '../sports_alerts/providers/sports_alert_providers.dart';

/// Extracts a team slug from a pattern ID generated by the sports library.
///
/// Pattern IDs follow the format: `gen_team_{league}_{team}_fx_{effectId}`
/// Team slugs in kTeamColors follow: `{league}_{team}`
///
/// Returns null if the pattern is not team-associated.
String? teamSlugFromPatternId(String patternId) {
  // Pattern IDs from sports library: gen_team_nfl_cowboys_fx_12
  if (!patternId.startsWith('gen_team_')) return null;

  final withoutPrefix = patternId.substring('gen_team_'.length);
  final fxIndex = withoutPrefix.indexOf('_fx_');
  if (fxIndex < 0) return null;

  final slug = withoutPrefix.substring(0, fxIndex);
  // Verify this slug exists in our team database.
  if (kTeamColors.containsKey(slug)) return slug;

  return null;
}

/// After a user applies a team-associated design, check if that team has a
/// game within 24 hours. If so, show a friendly prompt offering to enable
/// live scoring for the game.
///
/// Call this after a successful apply. It's a no-op if:
/// - The pattern is not team-associated
/// - No game found within 24h
/// - User declines
Future<void> maybePromptLiveScoring({
  required BuildContext context,
  required WidgetRef ref,
  required String patternId,
}) async {
  final teamSlug = teamSlugFromPatternId(patternId);
  if (teamSlug == null) return;

  final teamInfo = kTeamColors[teamSlug];
  if (teamInfo == null) return;

  // Check for a game within 24h.
  GameState? game;
  try {
    game = await ref.read(activeGameProvider(teamSlug).future);
  } catch (_) {
    return; // ESPN fetch failed — silently skip.
  }
  if (game == null) return;
  if (!context.mounted) return;

  final isLive = game.status == GameStatus.inProgress ||
      game.status == GameStatus.halftime;
  final isScheduled = game.status == GameStatus.scheduled;

  if (!isLive && !isScheduled) return; // Game is final — no point.

  final matchup = '${game.awayTeam} @ ${game.homeTeam}';
  final statusText = isLive
      ? 'Live now! ${game.homeScore} - ${game.awayScore}'
      : 'Today';

  final accepted = await showModalBottomSheet<bool>(
    context: context,
    backgroundColor: NexGenPalette.gunmetal,
    shape: const RoundedRectangleBorder(
      borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
    ),
    builder: (ctx) => _LiveScoringPromptSheet(
      teamName: teamInfo.teamName,
      matchup: matchup,
      statusText: statusText,
      isLive: isLive,
      primaryColor: teamInfo.primary,
      secondaryColor: teamInfo.secondary,
    ),
  );

  if (accepted != true) return;
  if (!context.mounted) return;

  // Add a ScoreAlertConfig for this team so the existing background
  // service picks it up and starts monitoring. If a config already
  // exists for this team, this is a no-op (the service de-duplicates).
  try {
    final existing = ref.read(sportsAlertConfigsProvider);
    final alreadyTracked = existing.any((c) => c.teamSlug == teamSlug);

    if (!alreadyTracked) {
      final config = ScoreAlertConfig(
        id: 'gameday_adhoc_$teamSlug',
        teamSlug: teamSlug,
        sport: teamInfo.sport,
        isEnabled: true,
      );
      await ref.read(sportsAlertConfigsProvider.notifier).addConfig(config);
    }

    if (context.mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
              'Live scoring enabled for ${teamInfo.teamName}! '
              'Your lights will celebrate every score.'),
          duration: const Duration(seconds: 3),
        ),
      );
    }
  } catch (_) {
    // Alert service not available — skip silently.
  }
}

// ---------------------------------------------------------------------------
// Prompt UI
// ---------------------------------------------------------------------------

class _LiveScoringPromptSheet extends StatelessWidget {
  final String teamName;
  final String matchup;
  final String statusText;
  final bool isLive;
  final Color primaryColor;
  final Color secondaryColor;

  const _LiveScoringPromptSheet({
    required this.teamName,
    required this.matchup,
    required this.statusText,
    required this.isLive,
    required this.primaryColor,
    required this.secondaryColor,
  });

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.fromLTRB(24, 16, 24, 24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // Handle bar
            Center(
              child: Container(
                width: 40,
                height: 4,
                decoration: BoxDecoration(
                  color: NexGenPalette.textMedium.withValues(alpha: 0.3),
                  borderRadius: BorderRadius.circular(2),
                ),
              ),
            ),
            const SizedBox(height: 20),

            // Team color accent bar
            Container(
              height: 4,
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [primaryColor, secondaryColor],
                ),
                borderRadius: BorderRadius.circular(2),
              ),
            ),
            const SizedBox(height: 20),

            // Icon
            Container(
              width: 56,
              height: 56,
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [
                    primaryColor.withValues(alpha: 0.3),
                    secondaryColor.withValues(alpha: 0.3),
                  ],
                ),
                shape: BoxShape.circle,
              ),
              child: const Icon(
                Icons.celebration_rounded,
                color: Colors.white,
                size: 28,
              ),
            ),
            const SizedBox(height: 16),

            // Title
            Text(
              isLive
                  ? '$teamName is playing right now!'
                  : '$teamName has a game today!',
              textAlign: TextAlign.center,
              style: const TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.w700,
                color: NexGenPalette.textHigh,
              ),
            ),
            const SizedBox(height: 8),

            // Matchup
            Text(
              matchup,
              textAlign: TextAlign.center,
              style: TextStyle(
                fontSize: 15,
                fontWeight: FontWeight.w500,
                color: NexGenPalette.textMedium,
              ),
            ),
            const SizedBox(height: 4),

            // Status
            Container(
              padding:
                  const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
              decoration: BoxDecoration(
                color: isLive
                    ? Colors.green.withValues(alpha: 0.15)
                    : NexGenPalette.cyan.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(12),
              ),
              child: Text(
                statusText,
                style: TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.w600,
                  color: isLive ? Colors.green : NexGenPalette.cyan,
                ),
              ),
            ),
            const SizedBox(height: 20),

            // Prompt text
            Text(
              'Want to enable live scoring effects? '
              'Your lights will celebrate every score during the game.',
              textAlign: TextAlign.center,
              style: TextStyle(
                fontSize: 14,
                color: NexGenPalette.textMedium,
                height: 1.5,
              ),
            ),
            const SizedBox(height: 24),

            // Buttons
            Row(
              children: [
                Expanded(
                  child: OutlinedButton(
                    onPressed: () => Navigator.pop(context, false),
                    style: OutlinedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 14),
                      side: BorderSide(
                          color:
                              NexGenPalette.textMedium.withValues(alpha: 0.3)),
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12)),
                    ),
                    child: const Text('No thanks',
                        style: TextStyle(color: NexGenPalette.textMedium)),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: ElevatedButton(
                    onPressed: () => Navigator.pop(context, true),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: primaryColor,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(vertical: 14),
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12)),
                    ),
                    child: const Text('Let\'s go!',
                        style: TextStyle(fontWeight: FontWeight.w700)),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
