// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWwqffD-ggRh5-IYwR2ldjaztd-Jgz0JY',
    appId: '1:1036323013258:web:5a6ad82a0dcdd7c4186373',
    messagingSenderId: '1036323013258',
    projectId: 'icrt6menwsv2d8all8oijs021b06s5',
    authDomain: 'icrt6menwsv2d8all8oijs021b06s5.firebaseapp.com',
    storageBucket: 'icrt6menwsv2d8all8oijs021b06s5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2VhrbVD1lBbs_b_JuCkjLa1Yh_AsbWJs',
    appId: '1:1036323013258:android:4837f6a336b54f2e186373',
    messagingSenderId: '1036323013258',
    projectId: 'icrt6menwsv2d8all8oijs021b06s5',
    storageBucket: 'icrt6menwsv2d8all8oijs021b06s5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiRUF0Hd2D5wIW1fyLsaO3WQTeJq35wFY',
    appId: '1:1036323013258:ios:e1ba33c2548e6589186373',
    messagingSenderId: '1036323013258',
    projectId: 'icrt6menwsv2d8all8oijs021b06s5',
    storageBucket: 'icrt6menwsv2d8all8oijs021b06s5.firebasestorage.app',
    iosBundleId: 'com.nexgenled.command',
  );
}
