import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:nexgen_command/features/ai/lumina_lighting_suggestion.dart';
import 'package:nexgen_command/features/ai/pixel_strip_preview.dart';
import 'package:nexgen_command/features/schedule/schedule_plan_controller.dart';
import 'package:nexgen_command/theme.dart';
import 'package:nexgen_command/utils/effect_display_meta.dart';

/// Individual day card within a [SchedulePlanCard].
///
/// Displays a rich preview of the scheduled lighting design:
///  - Row 1: Design name + time range
///  - Row 2: Color dot strip + effect badge
///  - Row 3: Effect motion description
///
/// Uses a staggered slide-in animation controlled by [animationDelay].
///
/// Supports swipe-left to dismiss. For autopilot entries, the swipe reveals
/// a choice between removing this week's instance or disabling the autopilot
/// trigger entirely.
class ScheduleDayRow extends ConsumerStatefulWidget {
  /// The day entry to display.
  final SchedulePlanDay day;

  /// Index of this day in the plan (for edit callbacks).
  final int dayIndex;

  /// Whether this day is currently being edited inline.
  final bool isEditing;

  /// Called when the user taps the edit icon.
  final VoidCallback? onEdit;

  /// Called when the user taps the card body to open the detail sheet.
  final VoidCallback? onTap;

  /// Time range label (e.g. "4:00 PM – 10:00 PM"), from the parent plan.
  final String? timeRange;

  /// Stagger delay for the entrance animation.
  final Duration animationDelay;

  /// Whether this entry was generated by autopilot.
  final bool isAutopilot;

  /// The autopilot event type label (e.g. "Game Day", "Holiday").
  /// Used in the "Disable autopilot for [eventType]" option.
  final String? autopilotEventType;

  /// Called when the user confirms deletion of a non-autopilot entry.
  final VoidCallback? onDelete;

  /// Called when the user chooses "Remove this week only" for an autopilot entry.
  final VoidCallback? onRemoveThisWeek;

  /// Called when the user chooses "Disable autopilot for [eventType]".
  final VoidCallback? onDisableAutopilot;

  const ScheduleDayRow({
    super.key,
    required this.day,
    required this.dayIndex,
    this.isEditing = false,
    this.onEdit,
    this.onTap,
    this.timeRange,
    this.animationDelay = Duration.zero,
    this.isAutopilot = false,
    this.autopilotEventType,
    this.onDelete,
    this.onRemoveThisWeek,
    this.onDisableAutopilot,
  });

  @override
  ConsumerState<ScheduleDayRow> createState() => _ScheduleDayRowState();
}

class _ScheduleDayRowState extends ConsumerState<ScheduleDayRow>
    with SingleTickerProviderStateMixin {
  late AnimationController _slideController;
  late Animation<Offset> _slideAnimation;
  late Animation<double> _fadeAnimation;

  @override
  void initState() {
    super.initState();

    _slideController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 350),
    );

    _slideAnimation = Tween<Offset>(
      begin: const Offset(0.0, 0.15),
      end: Offset.zero,
    ).animate(CurvedAnimation(
      parent: _slideController,
      curve: Curves.easeOutCubic,
    ));

    _fadeAnimation = Tween<double>(begin: 0.0, end: 1.0).animate(
      CurvedAnimation(
        parent: _slideController,
        curve: Curves.easeOut,
      ),
    );

    // Stagger the entrance
    Future.delayed(widget.animationDelay, () {
      if (mounted) _slideController.forward();
    });
  }

  @override
  void dispose() {
    _slideController.dispose();
    super.dispose();
  }

  /// Extract display colors from the suggestion's wledPayload col array.
  List<Color> _extractColors() {
    final s = widget.day.suggestion;
    // Prefer the pre-extracted suggestion colors
    if (s.colors.isNotEmpty) return s.colors;
    // Fall back to parsing payload
    final payload = s.wledPayload;
    if (payload == null) return const [NexGenPalette.cyan];
    final seg = payload['seg'];
    if (seg is List && seg.isNotEmpty && seg.first is Map) {
      final col = (seg.first as Map)['col'];
      if (col is List && col.isNotEmpty) {
        return col
            .whereType<List>()
            .where((c) => c.length >= 3)
            .map((c) => Color.fromARGB(
                  255,
                  (c[0] as num).toInt().clamp(0, 255),
                  (c[1] as num).toInt().clamp(0, 255),
                  (c[2] as num).toInt().clamp(0, 255),
                ))
            .toList();
      }
    }
    return const [NexGenPalette.cyan];
  }

  /// Extract the WLED effect ID from the suggestion.
  int _extractFxId() {
    final s = widget.day.suggestion;
    // Use the suggestion's effect info directly
    if (s.effect.id != 0 || s.effect.name == 'Solid') return s.effect.id;
    // Fall back to parsing payload
    final payload = s.wledPayload;
    if (payload == null) return 0;
    final seg = payload['seg'];
    if (seg is List && seg.isNotEmpty && seg.first is Map) {
      final fx = (seg.first as Map)['fx'];
      if (fx is int) return fx;
    }
    return 0;
  }

  @override
  Widget build(BuildContext context) {
    final colors = _extractColors();
    final fxId = _extractFxId();
    final meta = EffectDisplayMeta.fromId(fxId);
    final s = widget.day.suggestion;

    final cardContent = GestureDetector(
      onTap: widget.onTap,
      behavior: HitTestBehavior.opaque,
      child: Container(
        margin: const EdgeInsets.only(bottom: 8),
        padding: const EdgeInsets.all(10),
        decoration: BoxDecoration(
          color: widget.isEditing
              ? NexGenPalette.cyan.withValues(alpha: 0.06)
              : const Color(0xFF111821),
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: widget.isEditing
                ? NexGenPalette.cyan.withValues(alpha: 0.35)
                : NexGenPalette.line.withValues(alpha: 0.3),
            width: 0.5,
          ),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // ---- Row 1: Day badge + design name + time range ----
            _buildRow1(meta),

            const SizedBox(height: 8),

            // ---- Row 2: Color dot strip + effect badge ----
            _buildRow2(colors, meta, s),

            const SizedBox(height: 6),

            // ---- Row 3: Motion description ----
            _buildRow3(meta),
          ],
        ),
      ),
    );

    final hasDismiss = widget.onDelete != null ||
        widget.onRemoveThisWeek != null ||
        widget.onDisableAutopilot != null;

    return SlideTransition(
      position: _slideAnimation,
      child: FadeTransition(
        opacity: _fadeAnimation,
        child: hasDismiss
            ? Dismissible(
                key: ValueKey('dismiss_${widget.day.key}'),
                direction: DismissDirection.endToStart,
                confirmDismiss: (_) => _confirmDismiss(context),
                background: const SizedBox.shrink(),
                secondaryBackground: _buildSwipeBackground(),
                child: cardContent,
              )
            : cardContent,
      ),
    );
  }

  // ── Swipe dismiss logic ──────────────────────────────────────────────────────

  Widget _buildSwipeBackground() {
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(12),
        color: Colors.red.shade900.withValues(alpha: 0.6),
      ),
      alignment: Alignment.centerRight,
      padding: const EdgeInsets.only(right: 20),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            widget.isAutopilot ? 'Manage' : 'Delete',
            style: const TextStyle(
              color: Colors.white70,
              fontSize: 12,
              fontWeight: FontWeight.w600,
            ),
          ),
          const SizedBox(width: 6),
          Icon(
            widget.isAutopilot
                ? Icons.smart_toy_outlined
                : CupertinoIcons.delete,
            color: Colors.white70,
            size: 18,
          ),
        ],
      ),
    );
  }

  Future<bool> _confirmDismiss(BuildContext context) async {
    if (widget.isAutopilot) {
      return await _showAutopilotOptions(context);
    }
    return await _showDeleteConfirmation(context);
  }

  Future<bool> _showDeleteConfirmation(BuildContext context) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: NexGenPalette.gunmetal90,
        title: const Text('Remove this day?'),
        content: Text(
          'Delete "${widget.day.designName}" from the schedule?',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(false),
            child: const Text('Cancel'),
          ),
          FilledButton.tonal(
            onPressed: () => Navigator.of(ctx).pop(true),
            style: FilledButton.styleFrom(
              backgroundColor: Colors.red.shade700,
            ),
            child: const Text('Delete'),
          ),
        ],
      ),
    );
    if (confirmed == true) {
      widget.onDelete?.call();
    }
    return false; // never auto-remove — callback handles state
  }

  Future<bool> _showAutopilotOptions(BuildContext context) async {
    final eventLabel =
        widget.autopilotEventType ?? 'this event type';

    await showModalBottomSheet<void>(
      context: context,
      backgroundColor: NexGenPalette.gunmetal90,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
      ),
      builder: (ctx) => SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 20),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Header
              Row(
                children: [
                  Icon(Icons.smart_toy_rounded,
                      color: NexGenPalette.cyan, size: 20),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      'Autopilot: ${widget.day.designName}',
                      style: const TextStyle(
                        color: NexGenPalette.textHigh,
                        fontSize: 15,
                        fontWeight: FontWeight.w700,
                      ),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              // Option 1: Remove this week only
              _AutopilotOptionTile(
                icon: Icons.event_busy_rounded,
                label: 'Remove this week only',
                subtitle:
                    'Autopilot will suggest this again next time it applies.',
                onTap: () {
                  Navigator.of(ctx).pop();
                  widget.onRemoveThisWeek?.call();
                },
              ),
              const SizedBox(height: 8),

              // Option 2: Disable autopilot for event type
              _AutopilotOptionTile(
                icon: Icons.block_rounded,
                iconColor: Colors.red.shade400,
                label: 'Disable autopilot for $eventLabel',
                subtitle:
                    'Autopilot will stop generating entries for $eventLabel.',
                onTap: () {
                  Navigator.of(ctx).pop();
                  widget.onDisableAutopilot?.call();
                },
              ),
              const SizedBox(height: 12),

              // Cancel
              TextButton(
                onPressed: () => Navigator.of(ctx).pop(),
                child: const Text('Cancel'),
              ),
            ],
          ),
        ),
      ),
    );
    return false; // never auto-remove — callbacks handle state
  }

  /// Row 1: Day badge, design name, time range, edit icon
  Widget _buildRow1(EffectDisplayMeta meta) {
    return Row(
      children: [
        // Day badge
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
          decoration: BoxDecoration(
            color: NexGenPalette.cyan.withValues(alpha: 0.12),
            borderRadius: BorderRadius.circular(6),
          ),
          child: Text(
            '${widget.day.dayOfWeek} ${widget.day.dateLabel}',
            style: const TextStyle(
              fontSize: 11,
              fontWeight: FontWeight.w700,
              color: NexGenPalette.cyan,
              letterSpacing: 0.5,
            ),
          ),
        ),

        const SizedBox(width: 8),

        // Design name
        Expanded(
          child: Text(
            widget.day.designName,
            style: const TextStyle(
              fontSize: 13,
              fontWeight: FontWeight.w500,
              color: NexGenPalette.textHigh,
            ),
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
          ),
        ),

        // Time range (from parent plan)
        if (widget.timeRange != null) ...[
          const SizedBox(width: 6),
          Text(
            widget.timeRange!,
            style: TextStyle(
              fontSize: 10,
              color: NexGenPalette.textSecondary.withValues(alpha: 0.7),
            ),
          ),
        ],

        // Edit icon
        if (widget.onEdit != null)
          GestureDetector(
            onTap: widget.onEdit,
            behavior: HitTestBehavior.opaque,
            child: Padding(
              padding: const EdgeInsets.all(4),
              child: Icon(
                Icons.edit_outlined,
                size: 16,
                color: widget.isEditing
                    ? NexGenPalette.cyan
                    : NexGenPalette.textMedium.withValues(alpha: 0.5),
              ),
            ),
          ),
      ],
    );
  }

  /// Row 2: Pixel strip preview + effect badge pill
  Widget _buildRow2(List<Color> colors, EffectDisplayMeta meta,
      LuminaLightingSuggestion s) {
    return Row(
      children: [
        // Color dot strip
        Expanded(
          child: PixelStripPreview(
            colors: colors,
            effectType: s.effect.category,
            speed: s.speed ?? 0.5,
            brightness: s.brightness,
            pixelCount: 20,
            height: 32,
            borderRadius: 8,
            backgroundColor: const Color(0xFF0A0E14),
          ),
        ),

        const SizedBox(width: 8),

        // Effect badge pill
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
          decoration: BoxDecoration(
            color: const Color(0xFF0A0E14),
            borderRadius: BorderRadius.circular(10),
            border: Border.all(
              color: NexGenPalette.line.withValues(alpha: 0.4),
              width: 0.5,
            ),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                meta.name,
                style: TextStyle(
                  fontSize: 10,
                  fontWeight: FontWeight.w600,
                  color: colors.isNotEmpty
                      ? colors.first
                      : NexGenPalette.cyan,
                ),
              ),
              if (meta.isMotion) ...[
                const SizedBox(width: 3),
                Icon(
                  Icons.loop,
                  size: 10,
                  color: colors.isNotEmpty
                      ? colors.first.withValues(alpha: 0.7)
                      : NexGenPalette.cyan.withValues(alpha: 0.7),
                ),
              ],
            ],
          ),
        ),
      ],
    );
  }

  /// Row 3: Subtle motion description
  Widget _buildRow3(EffectDisplayMeta meta) {
    return Text(
      meta.motionDescription,
      style: TextStyle(
        fontSize: 10,
        color: NexGenPalette.textSecondary.withValues(alpha: 0.6),
        fontStyle: FontStyle.italic,
      ),
    );
  }
}

// ─── Autopilot option tile (used in the swipe bottom sheet) ─────────────────

class _AutopilotOptionTile extends StatelessWidget {
  final IconData icon;
  final Color? iconColor;
  final String label;
  final String subtitle;
  final VoidCallback onTap;

  const _AutopilotOptionTile({
    required this.icon,
    this.iconColor,
    required this.label,
    required this.subtitle,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.transparent,
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(10),
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(10),
            border: Border.all(
              color: NexGenPalette.line.withValues(alpha: 0.4),
            ),
          ),
          child: Row(
            children: [
              Icon(icon,
                  color: iconColor ?? NexGenPalette.cyan, size: 22),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      label,
                      style: const TextStyle(
                        color: NexGenPalette.textHigh,
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      subtitle,
                      style: TextStyle(
                        color: NexGenPalette.textSecondary.withValues(alpha: 0.7),
                        fontSize: 11,
                      ),
                    ),
                  ],
                ),
              ),
              Icon(Icons.chevron_right_rounded,
                  color: NexGenPalette.textMedium.withValues(alpha: 0.5),
                  size: 20),
            ],
          ),
        ),
      ),
    );
  }
}
