#!/usr/bin/env python3
"""Lumina Bridge OTA signing tool.

Run with the PlatformIO Python, which already has `cryptography`:
    ~/.platformio/penv/Scripts/python.exe tools/sign_firmware.py <command> ...

Commands
  keygen  --private <path> --header <src/ota_pubkey.h>
          New ECDSA P-256 key pair. The private key is written ONLY to
          --private (refused if it resolves inside this git repository, which
          is public); the public key becomes a C header for the firmware.

  sign    --bin <firmware.bin> --version <x.y.z> --key <private.pem>
          [--board esp32dev] [--allow-bench] --out <manifest.json>
          Checks the image really is that version/board (markers compiled in
          by main.cpp), refuses a bench image unless --allow-bench, signs
              lumina-bridge-fw|v1|<board>|<version>|<size>|<sha256>
          and writes the manifest publish_firmware.js uploads. The download
          URL is not signed (the bridge checks size + SHA-256 of whatever it
          downloads), so hosting is decided at publish time, not here.

  verify  --manifest <manifest.json> --pub <public.pem | ota_pubkey.h> [--bin <firmware.bin>]
          Re-checks a manifest (and optionally the image) exactly as the
          bridge does. Use before every publish.

Nothing here touches the network or Firebase.
"""

import argparse
import base64
import hashlib
import json
import os
import re
import subprocess
import sys

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec

MESSAGE_FORMAT = "lumina-bridge-fw|v1|{board}|{version}|{size}|{sha256}"
VERSION_RE = re.compile(r"^\d+\.\d+\.\d+$")


def canonical_message(board, version, size, sha256_hex):
    return MESSAGE_FORMAT.format(board=board, version=version, size=size,
                                 sha256=sha256_hex.lower()).encode("ascii")


def repo_root():
    try:
        out = subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True,
                             text=True, check=True, cwd=os.path.dirname(os.path.abspath(__file__)))
        return os.path.realpath(out.stdout.strip())
    except Exception:
        return None


def inside(path, root):
    path = os.path.realpath(path)
    return root is not None and os.path.commonpath([path, root]) == root


def cmd_keygen(args):
    root = repo_root()
    if inside(args.private, root):
        sys.exit(f"refusing: {args.private} is inside the git repository ({root}), which is public. "
                 "Write the private key somewhere outside it.")
    if os.path.exists(args.private):
        sys.exit(f"refusing to overwrite existing private key {args.private}")
    key = ec.generate_private_key(ec.SECP256R1())
    pem_priv = key.private_bytes(serialization.Encoding.PEM,
                                 serialization.PrivateFormat.PKCS8,
                                 serialization.NoEncryption())
    fd = os.open(args.private, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "wb") as f:
        f.write(pem_priv)
    pem_pub = key.public_key().public_bytes(serialization.Encoding.PEM,
                                            serialization.PublicFormat.SubjectPublicKeyInfo).decode()
    guard = os.path.basename(args.header).upper().replace(".", "_")
    lines = "".join(f'  "{line}\\n" \\\n' for line in pem_pub.strip().splitlines())
    header = (f"// Generated by tools/sign_firmware.py keygen. PUBLIC key only.\n"
              f"#ifndef {guard}\n#define {guard}\n\n"
              f"#define OTA_SIGNING_PUBKEY_PEM \\\n{lines}  \"\"\n\n#endif\n")
    with open(args.header, "w", newline="\n") as f:
        f.write(header)
    print(f"private key -> {args.private} (keep offline; back it up)")
    print(f"public key header -> {args.header}")


def load_public_key(path):
    data = open(path, "rb").read()
    if path.endswith(".h"):
        # Re-assemble the PEM from the C string literal lines.
        parts = re.findall(rb'"((?:[^"\\]|\\.)*)"', data)
        data = b"".join(p.replace(b"\\n", b"\n") for p in parts)
    return serialization.load_pem_public_key(data)


def image_facts(bin_path):
    blob = open(bin_path, "rb").read()
    return blob, len(blob), hashlib.sha256(blob).hexdigest()


def check_markers(blob, version, board, allow_bench):
    if f"LUMINA_BRIDGE_FW_VERSION={version}\0".encode() not in blob:
        found = re.findall(rb"LUMINA_BRIDGE_FW_VERSION=([^\x00]{1,32})\x00", blob)
        sys.exit(f"image does not say it is version {version} (it says {found or 'nothing'}). "
                 "Build with the matching BRIDGE_FIRMWARE_VERSION.")
    if f"LUMINA_BRIDGE_FW_BOARD={board}\0".encode() not in blob:
        sys.exit(f"image is not built for board {board}")
    if b"/api/debug/" in blob and not allow_bench:
        sys.exit("image contains /api/debug/ routes -- it is a BENCH build. "
                 "Refusing to sign it for the fleet (pass --allow-bench only for the bench key).")


def cmd_sign(args):
    if not VERSION_RE.match(args.version):
        sys.exit("version must be MAJOR.MINOR.PATCH")
    blob, size, sha = image_facts(args.bin)
    check_markers(blob, args.version, args.board, args.allow_bench)
    key = serialization.load_pem_private_key(open(args.key, "rb").read(), password=None)
    sig = key.sign(canonical_message(args.board, args.version, size, sha),
                   ec.ECDSA(hashes.SHA256()))
    manifest = {
        "version": args.version,
        "board": args.board,
        "size": size,
        "sha256": sha,
        "sig": base64.b64encode(sig).decode(),
        "bench": b"/api/debug/" in blob,
    }
    with open(args.out, "w", newline="\n") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    print(json.dumps({k: v for k, v in manifest.items() if k != "sig"}, indent=2))
    print(f"manifest -> {args.out}")


def cmd_verify(args):
    m = json.load(open(args.manifest))
    pub = load_public_key(args.pub)
    msg = canonical_message(m.get("board", "esp32dev"), m["version"], m["size"], m["sha256"])
    try:
        pub.verify(base64.b64decode(m["sig"]), msg, ec.ECDSA(hashes.SHA256()))
    except InvalidSignature:
        sys.exit("SIGNATURE INVALID for this public key")
    print("signature OK")
    if args.bin:
        blob, size, sha = image_facts(args.bin)
        if size != m["size"] or sha != m["sha256"].lower():
            sys.exit(f"image does NOT match manifest (size {size} vs {m['size']}, sha {sha})")
        check_markers(blob, m["version"], m.get("board", "esp32dev"), allow_bench=True)
        print("image matches manifest")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    k = sub.add_parser("keygen")
    k.add_argument("--private", required=True)
    k.add_argument("--header", required=True)
    s = sub.add_parser("sign")
    s.add_argument("--bin", required=True)
    s.add_argument("--version", required=True)
    s.add_argument("--key", required=True)
    s.add_argument("--board", default="esp32dev")
    s.add_argument("--allow-bench", action="store_true")
    s.add_argument("--out", required=True)
    v = sub.add_parser("verify")
    v.add_argument("--manifest", required=True)
    v.add_argument("--pub", required=True)
    v.add_argument("--bin")
    args = ap.parse_args()
    {"keygen": cmd_keygen, "sign": cmd_sign, "verify": cmd_verify}[args.cmd](args)


if __name__ == "__main__":
    main()
