import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:nexgen_command/models/commercial/brand_color.dart';
import 'package:nexgen_command/models/commercial/brand_signature.dart';

/// Per-business commercial brand profile, persisted at
/// /users/{uid}/brand_profile/brand.
///
/// Stored as a subcollection so it doesn't collide with the existing
/// `commercial_profile` map field on the user doc, which already holds
/// hours, channels, teams, and day-parts written by
/// CommercialOnboardingWizard.
///
/// A commercial customer can derive this profile from a [BrandLibraryEntry]
/// (via the Find Brand search added to BrandIdentityScreen in Part 4) or
/// build it from scratch by adding colors manually. Either path produces
/// the same shape — the [brandLibraryId] field distinguishes them.
class CommercialBrandProfile {
  /// Customer-facing company name. May differ from the library entry's
  /// canonical name (e.g. "State Farm - Oak Park" vs library "State Farm").
  final String companyName;

  /// Pointer back to /brand_library/{brandId} when the profile was seeded
  /// from a library entry. `null` when the customer entered colors
  /// manually with no library match.
  final String? brandLibraryId;

  /// Brand colors using the canonical [BrandColor] model. Same shape as
  /// the existing `commercial_profile.brand_colors` array on the user doc
  /// — this subcollection holds the richer, library-aware version.
  final List<BrandColor> colors;

  /// True when the customer has modified colors after deriving from the
  /// library entry (used to drive the "Submit color correction" prompt
  /// in BrandSetupScreen).
  final bool customized;

  /// When the customer last modified colors. Null until first edit.
  final DateTime? customizedAt;

  /// Uid of the user who last edited the colors. Null until first edit.
  final String? customizedBy;

  /// Lighting signature for this profile — usually inherited from the
  /// library entry but can be regenerated locally in BrandSetupScreen.
  final BrandSignature signature;

  /// Names of favorites auto-generated by [BrandDesignGenerator] (Part 5).
  /// Stored on the profile so the Brand tab can list them with one
  /// Firestore read instead of querying favorites by naming convention.
  final List<String> generatedDesigns;

  /// Uid of the installer who pre-seeded this profile during the
  /// CommercialOnboardingWizard, if any. Null when the customer set up
  /// brand identity themselves.
  final String? createdByInstaller;

  /// When the profile doc was first written.
  final DateTime createdAt;

  const CommercialBrandProfile({
    required this.companyName,
    this.brandLibraryId,
    this.colors = const [],
    this.customized = false,
    this.customizedAt,
    this.customizedBy,
    this.signature = const BrandSignature(),
    this.generatedDesigns = const [],
    this.createdByInstaller,
    required this.createdAt,
  });

  factory CommercialBrandProfile.fromJson(Map<String, dynamic> json) {
    return CommercialBrandProfile(
      companyName: (json['company_name'] as String?) ?? '',
      brandLibraryId: json['brand_library_id'] as String?,
      colors: (json['colors'] as List?)
              ?.whereType<Map<String, dynamic>>()
              .map((e) => BrandColor.fromJson(e))
              .toList() ??
          const [],
      customized: (json['customized'] as bool?) ?? false,
      customizedAt: (json['customized_at'] as Timestamp?)?.toDate(),
      customizedBy: json['customized_by'] as String?,
      signature: json['signature'] is Map<String, dynamic>
          ? BrandSignature.fromJson(json['signature'] as Map<String, dynamic>)
          : const BrandSignature(),
      generatedDesigns: (json['generated_designs'] as List?)
              ?.map((e) => e.toString())
              .toList() ??
          const [],
      createdByInstaller: json['created_by_installer'] as String?,
      createdAt:
          (json['created_at'] as Timestamp?)?.toDate() ?? DateTime.now(),
    );
  }

  factory CommercialBrandProfile.fromFirestore(DocumentSnapshot<Object?> doc) {
    final raw = doc.data();
    final data = raw is Map<String, dynamic>
        ? Map<String, dynamic>.from(raw)
        : <String, dynamic>{};
    return CommercialBrandProfile.fromJson(data);
  }

  Map<String, dynamic> toJson() => {
        'company_name': companyName,
        if (brandLibraryId != null) 'brand_library_id': brandLibraryId,
        'colors': colors.map((e) => e.toJson()).toList(),
        'customized': customized,
        if (customizedAt != null) 'customized_at': Timestamp.fromDate(customizedAt!),
        if (customizedBy != null) 'customized_by': customizedBy,
        'signature': signature.toJson(),
        'generated_designs': generatedDesigns,
        if (createdByInstaller != null) 'created_by_installer': createdByInstaller,
        'created_at': Timestamp.fromDate(createdAt),
      };

  CommercialBrandProfile copyWith({
    String? companyName,
    String? brandLibraryId,
    List<BrandColor>? colors,
    bool? customized,
    DateTime? customizedAt,
    String? customizedBy,
    BrandSignature? signature,
    List<String>? generatedDesigns,
    String? createdByInstaller,
    DateTime? createdAt,
  }) {
    return CommercialBrandProfile(
      companyName: companyName ?? this.companyName,
      brandLibraryId: brandLibraryId ?? this.brandLibraryId,
      colors: colors ?? this.colors,
      customized: customized ?? this.customized,
      customizedAt: customizedAt ?? this.customizedAt,
      customizedBy: customizedBy ?? this.customizedBy,
      signature: signature ?? this.signature,
      generatedDesigns: generatedDesigns ?? this.generatedDesigns,
      createdByInstaller: createdByInstaller ?? this.createdByInstaller,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  /// Convenience accessor for the primary brand color, mirroring the
  /// helper on [BrandLibraryEntry].
  BrandColor? get primaryColor {
    for (final c in colors) {
      if (c.roleTag.toLowerCase() == 'primary') return c;
    }
    return colors.isNotEmpty ? colors.first : null;
  }

  /// True when the profile was derived from a /brand_library entry. Used
  /// by the UI to decide whether to show the "Submit color correction"
  /// affordance (only useful when there is a library entry to correct).
  bool get hasLibraryOrigin => brandLibraryId != null && brandLibraryId!.isNotEmpty;
}
