import 'package:flutter/material.dart';

class WledStateModel {
  final bool isOn;
  final int brightness; // 0-255
  final int speed; // 0-255
  final Color color;
  final bool connected;
  final int warmWhite; // 0-255
  final bool supportsRgbw;
  final int effectId; // WLED fx value (0-255)
  final int paletteId; // WLED palette value

  const WledStateModel({
    required this.isOn,
    required this.brightness,
    required this.speed,
    required this.color,
    required this.connected,
    required this.warmWhite,
    required this.supportsRgbw,
    this.effectId = 0,
    this.paletteId = 0,
  });

  WledStateModel copyWith({
    bool? isOn,
    int? brightness,
    int? speed,
    Color? color,
    bool? connected,
    int? warmWhite,
    bool? supportsRgbw,
    int? effectId,
    int? paletteId,
  }) =>
      WledStateModel(
        isOn: isOn ?? this.isOn,
        brightness: brightness ?? this.brightness,
        speed: speed ?? this.speed,
        color: color ?? this.color,
        connected: connected ?? this.connected,
        warmWhite: warmWhite ?? this.warmWhite,
        supportsRgbw: supportsRgbw ?? this.supportsRgbw,
        effectId: effectId ?? this.effectId,
        paletteId: paletteId ?? this.paletteId,
      );

  /// Get the effect name based on effectId
  String get effectName => kEffectNames[effectId] ?? 'Effect #$effectId';

  static WledStateModel initial() => const WledStateModel(
        isOn: false,
        brightness: 128,
        speed: 128,
        color: Colors.white,
        connected: false,
        warmWhite: 0,
        supportsRgbw: false,
        effectId: 0,
        paletteId: 0,
      );
}

/// Common WLED effect names by ID
const Map<int, String> kEffectNames = {
  0: 'Solid',
  1: 'Blink',
  2: 'Breathe',
  3: 'Wipe',
  4: 'Wipe Random',
  5: 'Random Colors',
  6: 'Sweep',
  7: 'Dynamic',
  8: 'Colorloop',
  9: 'Rainbow',
  10: 'Scan',
  11: 'Scan Dual',
  12: 'Fade',
  13: 'Theater',
  14: 'Theater Rainbow',
  15: 'Running',
  16: 'Saw',
  17: 'Twinkle',
  18: 'Dissolve',
  19: 'Dissolve Rnd',
  20: 'Sparkle',
  21: 'Sparkle Dark',
  22: 'Sparkle+',
  23: 'Strobe',
  24: 'Strobe Rainbow',
  25: 'Strobe Mega',
  26: 'Blink Rainbow',
  27: 'Android',
  28: 'Chase',
  29: 'Chase Random',
  30: 'Chase Rainbow',
  31: 'Chase Flash',
  32: 'Chase Flash Rnd',
  33: 'Rainbow Runner',
  34: 'Colorful',
  35: 'Traffic Light',
  36: 'Sweep Random',
  37: 'Candle',
  38: 'Candle Multi',
  39: 'Shimmers',
  40: 'BPM',
  41: 'Running',
  42: 'Fireworks',
  43: 'Twinkle',
  44: 'Twinkle Random',
  45: 'Twinkle Fade',
  46: 'Twinkle Fade Rnd',
  47: 'Sparkle+',
  48: 'Strobe Mega',
  49: 'Popcorn',
  50: 'Drip',
  51: 'Lighthouse',
  52: 'Fireworks',
  53: 'Fireworks 1D',
  54: 'Fireworks Starburst',
  55: 'Fire 2012',
  56: 'Colorwaves',
  57: 'Bpm',
  58: 'Fill Noise',
  59: 'Noise 1',
  60: 'Noise 2',
  61: 'Noise 3',
  62: 'Noise 4',
  63: 'Colortwinkles',
  64: 'Lake',
  65: 'Chase',
  66: 'Chase Fade',
  67: 'Chase Rnd',
  68: 'Chase Rnd Fade',
  69: 'Fill Chase',
  70: 'Twinkle Fox',
  71: 'Pride 2015',
  72: 'Sparkle',
  73: 'Juggle',
  74: 'Palette',
  75: 'Fire 2012',
  76: 'Colorwaves',
  77: 'Meteor',
  78: 'Meteor Smooth',
  79: 'Railway',
  80: 'Ripple',
  81: 'Twinklefox',
  82: 'Twinklecat',
  83: 'Halloween Eyes',
  84: 'Solid Pattern',
  85: 'Solid Pattern Tri',
  86: 'Spots',
  87: 'Spots Fade',
  88: 'Glitter',
  89: 'Candle',
  90: 'Bounce',
  91: 'Fireworks',
  92: 'Rain',
  93: 'Merry Christmas',
  94: 'Fire Flicker',
  95: 'Ripple',
  96: 'Heartbeat',
  97: 'Pacifica',
  98: 'Candle Multi',
  99: 'Solid Glitter',
  100: 'Sunrise',
  101: 'Phased',
  102: 'Twinkleup',
  103: 'Noise Pal',
  104: 'Sine',
  105: 'Phased Noise',
  106: 'Flow',
  107: 'Chunchun',
  108: 'Dancing Shadows',
  109: 'Washing Machine',
  110: 'Flow',
  111: 'Blobs',
  112: 'Scrolling Text',
  113: '2D Drift Rose',
  114: '2D Distortion Waves',
  115: '2D Soap',
  116: '2D Octopus',
  117: '2D Waving Cell',
  118: 'Pulsate',
  119: 'Sinelon',
  120: 'Sinelon Rainbow',
};
